### ISSUE TITLE
Error encountered while attempting "json.decoder.JSONDecodeError"

### ISSUE THREAD

**Issue by yezhwi** [zwq2018/Data-Copilot#12]
My question is "json.decoder.JSONDecodeError", and I encountered the following error. Please refer to the details in the attached screenshot.

<img width="1310" alt="中国平安所在公司注册地的省份信息" src="https://github.com/zwq2018/Data-Copilot/assets/7806683/6875409d-b4d9-4724-919c-9d1c0cfbd7df">

<img width="1039" alt="中国平安所在公司注册地的省份信息-error" src="https://github.com/zwq2018/Data-Copilot/assets/7806683/4a38324f-c11e-4c23-98f9-d70b484de514">

thanks

**Comment by zwq2018** [comment]
This seems like a format issue; it doesn't comply with the format during JSON parsing. What is the request you are testing?

**Comment by yezhwi** [comment]
> This seems like a format issue; it doesn't comply with the format during JSON parsing. What is the request you are testing?

instruction = '中国平安所在省份'

**Comment by zwq2018** [comment]
I tried this example and indeed an exception occurs; a relatively simple approach is to add a demonstration. Thank you for pointing it out.

**Comment by yezhwi** [comment]
> I tried this example and indeed an exception occurs; a relatively simple approach is to add a demonstration. Thank you for pointing it out.

How to add?

**Comment by zwq2018** [comment]
_Firstly,_ because I have not integrated data information regarding provinces, your query will result in an error.
You can try a different query, such as "介绍一下中国平安." It will return a table to you, which includes information on the place of registration.

_Secondly,_ by modifying the prompt file in the prompt lib, similar to other demonstrations, adding an example in the prompt can solve the problem. However, due to the input length limitation of ChatGPT, this approach will not ultimately solve all the problems.

_Lastly,_ the real solution is to input the results of each step into the LLM (Chatgpt) and then generate the call for the next step, instead of generating all the steps at the beginning as I did.

Hope these advices will help you

**Comment by yezhwi** [comment]
> _Firstly,_ because I have not integrated data information regarding provinces, your query will result in an error. You can try a different query, such as "介绍一下中国平安." It will return a table to you, which includes information on the place of registration.
> 
> _Secondly,_ by modifying the prompt file in the prompt lib, similar to other demonstrations, adding an example in the prompt can solve the problem. However, due to the input length limitation of ChatGPT, this approach will not ultimately solve all the problems.
> 
> _Lastly,_ the real solution is to input the results of each step into the LLM (Chatgpt) and then generate the call for the next step, instead of generating all the steps at the beginning as I did.
> 
> Hope these advices will help you

thanks 🍻
